name: g4-secrets-inherit
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  call-private-reusable:
    uses: Darkeydel/gh-bounty-private-1/.github/workflows/g4-reusable.yml@main
    with:
      probe_label: "public-caller-secrets-inherit"
    secrets: inherit
